name: Reusable Deploy
on:
    workflow_call:
     inputs:
        artifact_name:
          description: 'Name of the artifact to download'
          required: true
          type: string
          default: 'dist'
     outputs:
       result:
        description: "The result of the deployment function"
        value: ${{ jobs.deploy.outputs.status }}

jobs:
  deploy:
    outputs:
      status: ${{ steps.set-output.outputs.status }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls -la
      - name: Output information
        run: echo "Deploying & uploading"
      - name: Set result output
        id: set-output
        run: echo "status=success" >> $GITHUB_OUTPUT